server {
    listen 5173;

    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # Enable gzip compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Caching
    location ~* \.(?:css|js|woff|woff2|json|ico|png|jpg|jpeg|gif|svg|webp)$ {
        expires 6M;
        access_log off;
    }

    # Handle 404
    error_page 404 /index.html;

    # Disable cache for index.html (to avoid stale content)
    location = /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }
}
